---
- name: Install mysql packages
  dnf:
    name: "{{ mysql_packages }}"
    state: present

- name: Install pymysql CentOS
  pip: name=pymysql state=present

- name: Start mysql service
  service:
    name: mysqld
    state: started
    enabled: true

- name: Unconditionally reboot the machine with all defaults
  reboot:
...

